# Generated by Django 4.2.4 on 2024-04-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_actor_race_alter_actor_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='cleaned',
            field=models.TextField(blank=True, default=''),
        ),
    ]
