# Generated by Django 4.2.4 on 2024-04-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_actor_no_named'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='lines_spoken',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
